force-app/main/default/objects/Case/fields/ZendeskTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZendeskTicketId__c</fullName>
    <description>Field to store the Zendesk Ticket Id.</description>
    <label>Zendesk Ticket Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/ZendeskTicketURL__c.field-meta.xml
<CustomField>
    <fullName>ZendeskTicketURL__c</fullName>
    <description>Field to store the Zendesk ticket URL on case.</description>
    <label>Zendesk Ticket URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CaseZendeskTicketInfo__e/CaseZendeskTicketInfo__e.object-meta.xml
<CustomObject>
    <description>Platform event to publish after zendesk api sends response back after creating a ticket for a case.</description>
    <label>CaseZendeskTicketInfo</label>
    <pluralLabel>CasesZendeskTicketInfo</pluralLabel>
</CustomObject>

force-app/main/default/objects/CaseZendeskTicketInfo__e/fields/API_Response__c.field-meta.xml
<CustomField>
    <fullName>API_Response__c</fullName>
    <description>Message received from Zendesk after a create ticket request is made.</description>
    <label>API Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CaseZendeskTicketInfo__e/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <description>Id of the case for which ticket is created in Zendesk.</description>
    <label>Case Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseZendeskTicketInfo__e/fields/Ticket_Id__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Id__c</fullName>
    <description>Id of ticket created in zendesk</description>
    <label>Ticket Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CaseZendeskTicketInfo__e/fields/Ticket_URL__c.field-meta.xml
<CustomField>
    <fullName>Ticket_URL__c</fullName>
    <description>Field to store zendesk ticket url.</description>
    <label>Ticket URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
public with sharing class CaseTriggerHandler {
    
    public static void handleAfterInsert(List<Case> listOfCases) {
        if(System.isFuture() || System.isBatch()){
            return;
        }

        Map<Id, Case> casesMap = new Map<Id, Case>([SELECT Id, Contact.Name, ContactEmail FROM Case WHERE Id IN :listOfCases]);
        for(Id caseId : casesMap.keySet()){
            Case c = casesMap.get(caseId);
        }
        for (Case newCase : listOfCases) {
            ZendeskTicketUtils.TicketWrapper wrapper = new ZendeskTicketUtils.TicketWrapper();
            wrapper.body = newCase.Description;
            wrapper.priority = newCase.Priority;
            wrapper.name = casesMap.get(newCase.Id).Contact.Name;
            wrapper.email = casesMap.get(newCase.Id).ContactEmail;
            wrapper.subject = newCase.Subject + '_' + newCase.Id;
            makeCallout(JSON.serialize(wrapper));
        }
    }

    @future(callout = true)
    private static void makeCallout(String wrapperString) {
        ZendeskTicketUtils.TicketWrapper wrapper = (ZendeskTicketUtils.TicketWrapper)JSON.deserialize(wrapperString, ZendeskTicketUtils.TicketWrapper.class);
        ZendeskTicketUtils.ResponseClass response = ZendeskTicketUtils.createTicket(wrapper);
        if(response.responseCode == 201) {
            String caseId = wrapper.subject.substringAfter('_');
            CaseZendeskTicketInfo__e eventToPublish = new CaseZendeskTicketInfo__e(API_Response__c=response.message, Case_Id__c=caseId, Ticket_Id__c=response.ticketId, Ticket_URL__c=response.ticketUrl);
            Database.SaveResult sr = EventBus.publish(eventToPublish);
            if(sr.isSuccess()) {
                System.debug('Successfully published event.');
            }
            else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
            }
        }
    }

    public static void updateTicketIdOnCases(List<Id> caseIds, Map<Id, CaseZendeskTicketInfo__e> caseIdToTicketMap) {
        List<Case> casesToUpdate = [SELECT Id, ZendeskTicketId__c FROM Case WHERE Id IN :caseIds];
        for (Case c : casesToUpdate) {
            c.ZendeskTicketId__c = caseIdToTicketMap.get(c.Id).Ticket_Id__c;
            c.ZendeskTicketURL__c = caseIdToTicketMap.get(c.Id).Ticket_URL__c;
        }
        update casesToUpdate;
    }
}